fix workflows

diff --git a/.github/workflows/build-deb.yml b/.github/workflows/build-deb.yml
--- a/.github/workflows/build-deb.yml
+++ b/.github/workflows/build-deb.yml
@@ -16,12 +16,17 @@ jobs:
         run: chmod +x ./build-deb.sh
 
       - name: Build and Release Debian Package
-        run: ./build-deb.sh
+        run: |
+          ./build-deb.sh
+          if [ $? -ne 0 ]; then
+            echo "Failed to build Debian package"
+            exit 1
+          fi
 
       - name: Copy deb files to artifact directory
-      run: |
-        mkdir -p artifacts
-        cp ./src/*.deb artifacts/
+        run: |
+          mkdir -p artifacts
+          cp ./src/*.deb artifacts/
 
       - name: Upload deb
         uses: actions/upload-artifact@v3
@@ -32,23 +37,21 @@ jobs:
   release:
     needs: [build]
     runs-on: ubuntu-latest
-
     steps:
-    - name: Download deb artifacts
-      uses: actions/download-artifact@v3
-      with:
-        name: deb
-        path: artifacts
+      - name: Download deb artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: deb
+          path: artifacts
 
-    - name: Create GitHub Release
-      id: create_release
-      run: |
-        file_path=$(ls artifacts/*.deb | head -n1)
-        filename=$(basename "$file_path")
-        package_name=$(echo "$filename" | cut -d_ -f1)
-        version=$(echo "$filename" | cut -d_ -f2)
-        date=$(date "+%Y-%m-%d %H:%M:%S")
-        gh release create "$package_name $version" artifacts/*.deb -t "ReleaseTitle: $package_name $version" -n "Released on $date"
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          
+      - name: Create GitHub Release
+        id: create_release
+        run: |
+          file_path=$(ls artifacts/*.deb | head -n1)
+          filename=$(basename "$file_path")
+          package_name=$(echo "$filename" | cut -d_ -f1)
+          version=$(echo "$filename" | cut -d_ -f2)
+          date=$(date "+%Y-%m-%d %H:%M:%S")
+          gh release create "$package_name $version" artifacts/*.deb -t "ReleaseTitle: $package_name $version" -n "Released on $date"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
